mod weapons;

use super::super::gear::Gear;
use std::collections::HashMap;
use strum_macros::EnumIter;

/// A HashMap<GearName, Gear> type alias.
pub type GearMap = HashMap<GearName, Gear>;

/// An enum of the name of every Gear.
#[derive(Debug, EnumIter, Hash, Eq, PartialEq, PartialOrd, Clone, Copy)]
pub enum GearName {
    FooBarBaz,
    Chinchompa,
    RedChinchompa,
    BlackChinchompa,
    DinhsBulwark,
    ToxicBlowpipe,
    VoidHelmet,
    VoidBody,
    VoidLegs,
    VoidGloves,
    EliteVoidBody,
    EliteVoidLegs,
    TumekensShadow,
    SanguinestiStaff,
    TridentOfTheSwamp,
    TridentOfTheSeas,
    SalveAmuletEI,
    SalveAmuletI,
    MysticSmokeStaff,
    SmokeBattlestaff,
    SeerCull,
    SlayerHelmetI,
    Arclight,
    Darklight,
    DragonHunterLance,
    DragonHunterCrossbow,
    CrawsBow,
    ViggorasChainmace,
    ThammaronsSceptre,
    TwistedBow,
    ObsidianHelm,
    ObsidianPlatebody,
    ObsidianPlatelegs,
    ObsidianDagger,
    ObsidianMace,
    ObsidianMaul,
    ObsidianSword,
    BerserkerNecklace,
    DharoksGreathelm,
    DharoksPlatebody,
    DharoksPlatelegs,
    DharoksGreataxe,
    LeafBladedSpear,
    LeafBladedSword,
    LeafBladedBattleaxe,
    Keris,
    KerisPartisan,
    KerisPartisanOfBreaching,
    KerisPartisanOfCorruption,
    KerisPartisanOfTheSun,
    CrystalHelm,
    CrystalBody,
    CrystalLegs,
    CrystalBow,
    BowOfFaerdhinen,
    InquisitorsGreatHelm,
    InquisitorsHauberk,
    InquisitorsPlateskirt,
    BrimstoneRing,
    AbyssalBludgeon,
    TomeOfFire,
    OsmumtensFang,
    BoneDagger,
    DorgeshuunCrossbow,
    DragonClaws,
    AbyssalDagger,
    DragonDagger,
    ScytheOfVitur,
    Hands,
    BronzeCrossbow,
    BluriteCrossbow,
    IronCrossbow,
    SteelCrossbow,
    MithrilCrossbow,
    AdamantCrossbow,
    RuneCrossbow,
    DragonCrossbow,
    ArmadylCrossbow,
    ZaryteCrossbow,
    RubyDragonBoltsE,
    RubyBoltsE,
    DiamondDragonBoltsE,
    DiamondBoltsE,
    DragonstoneDragonBoltsE,
    DragonstoneBoltsE,
    OnyxDragonBoltsE,
    OnyxBoltsE,
}
